### ISSUE TITLE
Issue while install of

### ISSUE THREAD

**Issue by thomasklein1975** [gazoodle/geckolib#34]
Hi,

I have these issue while try to install geckolib:

`pi@raspberrypi-iob:~ $ pip install geckolib
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting geckolib
  Using cached https://files.pythonhosted.org/packages/57/70/353b9fd028243adc08b8e56e263922e8828a3c2730bb27d50358ad37d802/geckolib-0.4.7.tar.gz
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-7d73lW/geckolib/setup.py", line 6, in <module>
        setuptools.setup()
      File "/tmp/pip-build-env-LmhH9N/lib/python2.7/site-packages/setuptools/__init__.py", line 162, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python2.7/distutils/core.py", line 124, in setup
        dist.parse_config_files()
      File "/tmp/pip-build-env-LmhH9N/lib/python2.7/site-packages/setuptools/dist.py", line 702, in parse_config_files
        ignore_option_errors=ignore_option_errors)
      File "/tmp/pip-build-env-LmhH9N/lib/python2.7/site-packages/setuptools/config.py", line 121, in parse_configuration
        meta.parse()
      File "/tmp/pip-build-env-LmhH9N/lib/python2.7/site-packages/setuptools/config.py", line 426, in parse
        section_parser_method(section_options)
      File "/tmp/pip-build-env-LmhH9N/lib/python2.7/site-packages/setuptools/config.py", line 399, in parse_section
        self[name] = value
      File "/tmp/pip-build-env-LmhH9N/lib/python2.7/site-packages/setuptools/config.py", line 184, in __setitem__
        value = parser(value)
      File "/tmp/pip-build-env-LmhH9N/lib/python2.7/site-packages/setuptools/config.py", line 515, in _parse_version
        version = self._parse_attr(value, self.package_dir)
      File "/tmp/pip-build-env-LmhH9N/lib/python2.7/site-packages/setuptools/config.py", line 349, in _parse_attr
        module = import_module(module_name)
      File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
        __import__(name)
      File "/tmp/pip-install-7d73lW/geckolib/src/geckolib/__init__.py", line 5, in <module>
        from .async_tasks import AsyncTasks
      File "/tmp/pip-install-7d73lW/geckolib/src/geckolib/async_tasks.py", line 14
        async def __aenter__(self):
                ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-7d73lW/geckolib/
pi@raspberrypi-iob:~ $ python --version
Python 2.7.16
pi@raspberrypi-iob:~ $ python3 --version
Python 3.7.3
pi@raspberrypi-iob:~ $
`

Maybe related to python version? But I have no idea what to do

**Comment by jak1502** [comment]
Try it with 'pip' in place of 'pip'

**Comment by thomasklein1975** [comment]
> Try it with 'pip' in place of 'pip'

sorry didnt get it

**Comment by thomasklein1975** [comment]
mean usage of pip3?

`pi@raspberrypi-iob:~ $ pip3 install geckolib
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: geckolib in /usr/local/lib/python3.7/dist-packages (0.4.7)
Requirement already satisfied: python-version>="3.7" in /usr/local/lib/python3.7/dist-packages (from geckolib) (0.0.2)
pi@raspberrypi-iob:~ $
`

**Comment by thomasklein1975** [comment]
now it is working. I can controll spa in gecko/python shell. :-)
 thx for your support & lib. Now I have to manage to controll spa in my iobroker instance.

**Comment by gazoodle** [comment]
I'll close this issue as it seems to be resolved now.
