### ISSUE TITLE
Endless E2000 External Lights

### ISSUE THREAD

**Issue by dgwilson** [gazoodle/geckolib#35]
This is the same issue reported here: https://github.com/gazoodle/gecko-home-assistant/issues/69

I've been attempting to change a local copy of the code to get the External Lights to work.
I don't know Python (sorry) and have made some assumptions on how a few things work.
I made changes to const.py to add support for UdL120 which I believe is the device that is the external lights.

2022-10-31 20:48:22,445 geckolib.driver.accessor INFO Value for UdL120 changed from OFF to ON
2022-10-31 20:48:22,445 geckolib.driver.observable DEBUG GeckoEnumStructAccessor 'UdL120': 'ON' changed from OFF to ON

 KEY_USER_EXTERNAL_LIGHT = "UdL120"          # DGW Nov 22    - # User devices are those that have a Ud in the tag name
 KEYPAD_LIGHT_EXTERNAL = 17              # DGW Nov 22 - value of 17 is guess work
      "L120": ("External Lights", KEYPAD_LIGHT_EXTERNAL, KEY_USER_EXTERNAL_LIGHT, DEVICE_CLASS_LIGHT),          # DGW Nov 22
        ("External LIGHT", "Lights Button", KEYPAD_LIGHT_EXTERNAL),     # DGW Nov 22

After connecting I only see "Lights"... and I was thinking I'd see Lights and External Lights
I'm also not certain if I can manually turn on/off UdL120

Connecting to spa `Wilson E2000 Swim Spa` at 192.168.11.112 ... connected!
Heater: Temperature 30.5°C, SetPoint 30.0°C, Real SetPoint 30.0°C, Operation Cooling
Lights: OFF
WaterCare: Waiting...
Smart Winter Mode:Risk: NO
Circulating Pump: ON
Ozone: OFF
Smart Winter Mode:Active: False
Filter Status:Clean: False
Filter Status:Purge: False
Economy Mode: False
Wilson E2000 Swim Spa$ LI ON
Turn device Lights ON
Wilson E2000 Swim Spa$

I'm guessing... hoping someone is able to lend some guidance on what I could try next.

**Comment by dgwilson** [comment]
Update:

set UdL120=ON
--- definately turned the external lights on


set UdL120=OFF
--- tuning the external lights off seems to not work - at least it hasn't worked after the last 23 minutes'


accessors
- to check

UdL120: ON
UdL120Time: 217

UdL120Time looks like a countdown timer in minutes

**Comment by kiwibayer** [comment]
@dgwilson did you had any further luck with this?

**Comment by dgwilson** [comment]
No luck at the end of the day... and I ended up uninstalling the main library. We'd be having an issue with the lights in the spa randomly not working... (like a really weird fault)... And since uninstalling the software that "fault" has gone away and the lights are working just fine.

by not working I mean turning them on via the physical control panel on the spa and that not working. Having the switch on (lights not working) and turning on one of the pumps and the lights would randomly work.

I finally did the uninstall and everything has worked as expected.

So, sorry - no progress on actually getting the integration working.

I have done Gecko surveys where I've feedback suggestions for improvements... especially with their app. Nothing has changed there. (I know that's not this project).

**Comment by kiwibayer** [comment]
Playing around with this a bit more following @dgwilson approach
@gazoodle wondering if you can point us into the right direction 
(and also a big thank you in getting this lib up, it's much appreciated) 

L120 is definitely the external light. 
Set UdL120=ON will turn it on and at the same time starts a 4 hour timer on UdL120Time (e.g. its set's UdL120Time to 240)
Once the timer runs out UdL120 will be set to OFF, likewise if we set UdL120 to OFF UdL120Time will be set to 0

I think it's fair to just ignore the timer for now .... 
@dgwilson regarding your issues, what pump are you talking about in the e2000? 
The circulation pump on the pool side or the pumps on the spa side? 


@gazoodle like David I'm assuming we will need to add this to the constant.py
are there any other areas where we would need to add further details?
can you help us finding the Keypad number for the external light?

from what I can see in the file we'll need: 

 # Accessor keys for SpaPackStruct
 KEY_USER_DEMAND_LIGHT120 = "UdLi120"
 
  # Gecko keypad constants
  # not too sure how we can get this one 
  
  # Pack outputs
 # Assuming we can use the current light class here 
  DEVICE_CLASS_LIGHT = "LIGHT"
  
  #new device under DEVICES
  "UdLI": ("External Lights", KEYPAD_LIGHT120(TBC), KEY_USER_DEMAND_LIGHT120, DEVICE_CLASS_LIGHT),
  
  #new button under BUTTONS
  ("External Light", "External Lights Button", KEYPAD_LIGHT120)

**Comment by gazoodle** [comment]
Thanks, this is useful info. Now the library has been refactored it’s in a much better place to do this work. I’ve got the simulator ready to help too. Useful would be four snapshots during the light times, one before, one just after turning on, one just before it being turned off and one after it gets turned off.

Also use the `refresh` command prior to `snapshot` to ensure the data is up to date.

**Comment by dgwilson** [comment]
Awesome. I’ll need to get the library setup again and remember/read how to do the snapshots.Might be a job for the weekend.- DavidOn 13 Feb 2025, at 19:51, gazoodle ***@***.***> wrote:﻿
Thanks, this is useful info. Now the library has been refactored it’s in a much better place to do this work. I’ve got the simulator ready to help too. Useful would be four snapshots during the light times, one before, one just after turning on, one just before it being turned off and one after it gets turned off.
Also use the refresh command prior to snapshot to ensure the data is up to date.

**Comment by dgwilson** [comment]
Sorry. Python isn't my native friendly place... and I'm having some issue getting things up and running again.
I'm doing this on macOS - which may present some additional challenges perhaps. I'm getting an error after launching GeckoShell.run()...   

(Gecko) Starting discovery process...Found 0 spas

Hmmm it should find 2 spas... or 2 x in.touch controllers.
OK, looks like my controllers were offline (red light). I've fixed that now.
This suggest the below output / behaviour should be different if no controllers are found.

`(venv) dgwilson@MBP-M2 ~ % python3 -m pip install git+https://github.com/gazoodle/geckolib.git
Collecting git+https://github.com/gazoodle/geckolib.git
  Cloning https://github.com/gazoodle/geckolib.git to /private/var/folders/hm/xh411kpn4t5cyv3pnfgvbzmh0000gn/T/pip-req-build-g82dv8km
  Running command git clone --filter=blob:none --quiet https://github.com/gazoodle/geckolib.git /private/var/folders/hm/xh411kpn4t5cyv3pnfgvbzmh0000gn/T/pip-req-build-g82dv8km
  Resolved https://github.com/gazoodle/geckolib.git to commit e521da3fa78205b94d3dabbd43d63227bcf2a8df
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: geckolib
  Building wheel for geckolib (pyproject.toml) ... done
  Created wheel for geckolib: filename=geckolib-1.0.1-py3-none-any.whl size=698381 sha256=b68f192a8fc6ee9b49fcc54be869ac92b1f2046af093f118bce0cc584f6a682c
  Stored in directory: /private/var/folders/hm/xh411kpn4t5cyv3pnfgvbzmh0000gn/T/pip-ephem-wheel-cache-5m1_bc36/wheels/aa/ce/d3/083d7de3f4b57ce71c5b1bc6dd6c589c6f8b89c6349aaf195c
Successfully built geckolib
Installing collected packages: geckolib
Successfully installed geckolib-1.0.1

[notice] A new release of pip is available: 25.0 -> 25.0.1
[notice] To update, run: pip install --upgrade pip
(venv) dgwilson@MBP-M2 ~ % python3
Python 3.13.2 (main, Feb  4 2025, 14:51:09) [Clang 16.0.0 (clang-1600.0.26.6)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from geckolib import GeckoShell
>>> GeckoShell.run()


        <Disclaimer>
        ----------------------------- USE AT YOUR OWN RISK -----------------------------

        This code will allow you to make changes to your spa configuration that is
        outside of what the app, top panel and side panel settings allow. I've not
        tested every setting and it might be that you prevent your spa pack from
        operating as it used to do.

        I strongly suggest dumping the configuration values with the "config" command
        and recording them somewhere safe.

        </Disclaimer>

    
Welcome to the Gecko shell. Type help or ? to list commands.

(Gecko) Starting discovery process...Found 0 spas
                                                 LOG> WARNING Try using the iOS or Android app to confirm they are functioning correctly

Exception in Thread-1 (run_async_loop):
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 1041, in _bootstrap_inner
    self.run()
    ~~~~~~~~^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 992, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dgwilson/path/to/venv/lib/python3.13/site-packages/geckolib/utils/async_command.py", line 47, in run_async_loop
    runner.run(self.process_commands())
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/base_events.py", line 712, in run_until_complete
    self.run_forever()
    ~~~~~~~~~~~~~~~~^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/base_events.py", line 683, in run_forever
    self._run_once()
    ~~~~~~~~~~~~~~^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/base_events.py", line 2040, in _run_once
    handle._run()
    ~~~~~~~~~~~^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dgwilson/path/to/venv/lib/python3.13/site-packages/geckolib/async_spa_manager.py", line 576, in _sequence_pump
    await self.async_locate_spas(self._spa_address)
  File "/Users/dgwilson/path/to/venv/lib/python3.13/site-packages/geckolib/async_spa_manager.py", line 295, in async_locate_spas
    await self._handle_event(
    ...<2 lines>...
    )
  File "/Users/dgwilson/path/to/venv/lib/python3.13/site-packages/geckolib/async_spa_manager.py", line 553, in _handle_event
    await self.handle_event(event, **kwargs)
  File "/Users/dgwilson/path/to/venv/lib/python3.13/site-packages/geckolib/utils/shell.py", line 92, in handle_event
    sys.exit(1)
    ~~~~~~~~^^^
SystemExit: 1

Traceback (most recent call last):
  File "<python-input-1>", line 1, in <module>
    GeckoShell.run()
    ~~~~~~~~~~~~~~^^
  File "/Users/dgwilson/path/to/venv/lib/python3.13/site-packages/geckolib/utils/shared_command.py", line 60, in run
    cmd.cmdloop()
    ~~~~~~~~~~~^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/cmd.py", line 134, in cmdloop
    line = input(self.prompt)
  File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/_pyrepl/readline.py", line 371, in input
    result = reader.readline(startup_hook=self.startup_hook)
  File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/_pyrepl/reader.py", line 802, in readline
    self.handle1()
    ~~~~~~~~~~~~^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/_pyrepl/reader.py", line 756, in handle1
    self.run_hooks()
    ~~~~~~~~~~~~~~^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/_pyrepl/reader.py", line 734, in run_hooks
    threading_hook()
    ~~~~~~~~~~~~~~^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/_pyrepl/_threading_handler.py", line 69, in __call__
    return self.show()
           ~~~~~~~~~^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/_pyrepl/_threading_handler.py", line 50, in show
    reader.prepare()
    ~~~~~~~~~~~~~~^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/_pyrepl/historical_reader.py", line 306, in prepare
    super().prepare()
    ~~~~~~~~~~~~~~~^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/_pyrepl/reader.py", line 650, in prepare
    self.do_cmd((cmd, []))
    ~~~~~~~~~~~^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/_pyrepl/reader.py", line 710, in do_cmd
    command.do()
    ~~~~~~~~~~^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/_pyrepl/commands.py", line 227, in do
    raise KeyboardInterrupt
KeyboardInterrupt
>>> 
`

**Comment by dgwilson** [comment]
Moving on... FYI on some weird formatting...

`Welcome to the Gecko shell. Type help or ? to list commands.

(Gecko) Starting discovery process...Found 2 spas
                                                 (Gecko) 1
*** Unknown syntax: 1
(Gecko) 2
*** Unknown syntax: 2
(Gecko) about

GeckoShell: A python program using GeckoLib library to drive Gecko enabled devices with in.touch2 communication modules
Library version v1.0.1
(Gecko) ?

Documented commands (type help <topic>):
========================================
about      eco   help     license  loglevel  peek      snapshot  watercare
accessors  exit  hexdump  list     manage    set       state   
discover   get   key      logfile  monitor   setpoint  version 

(Gecko) list
1. Wilson E2000 Swim Spa (192.168.10.32)
2. Wilson E2000 Spa (192.168.10.35)
(Gecko) manage 1
Connecting to spa `Wilson E2000 Swim Spa` at 192.168.10.32 ... (Gecko) connected to Wilson E2000 Swim Spa!
                                                                                                          Heater: Temperature 30.0°C, SetPoint 30.0°C, Real SetPoint 30.0°C, Operation Idle
                                                                                                                                                                                           Lig
                                                                                                                                                                                             W
                                                                                                                                                                                             S
                                                                                                                                                                                             C
                                                                                                                                                                                             O
                                                                                                                                                                                             S
                                                                                                                                                                                             F
                                                                                                                                                                                             F
                                                                                                                                                                                             H
                                                                                                                                                                                             E
                                                                                                                                                                                             E
                                                                                                                                                                                             W
Wilson E2000 Swim Spa$ `

**Comment by dgwilson** [comment]
I've got 5 other 6 snapshots as requested.
The last one, is with the external lights being turned on along with the internal lights.
And I can see your accessor messages being logged.
Interestingly it didn't seem to register the external lights being turned off between snapshot 3 and 4.

[E2000.log](https://github.com/user-attachments/files/18813336/E2000.log)

Happy to provide more info as required.

**Comment by gazoodle** [comment]
Thanks for that. I think that's enough data to ensure I handle it correctly. The simulator and iOS app seem to function as expected. Interestingly though, your data doesn't seem to have any pumps, blowers or other accessories. The iOS app only shows two lights. Is this what you'd expect?

**Comment by dgwilson** [comment]
> Interestingly though, your data doesn't seem to have any pumps, blowers or other accessories. The iOS app only shows two lights. Is this what you'd expect?The E2000 is a swim spa. It’s basically a pool and a spa split in two.For this test I only connected to the swim side. There is no pump control. And the swim machine is controlled through separate remotes and also WiFi (add on). There is no integrated controller.The Spa side has 2 x pumps that I can turn on/off for jets and manual controls for air injection.Using the in.touch app to switch between the two is horrible… in that its connection performance is really really bad.- DavidSent from my iPadOn 17 Feb 2025, at 00:47, gazoodle ***@***.***> wrote:﻿
  Thanks for that. I think that's enough data to ensure I handle it correctly. The simulator and iOS app seem to function as expected. Interestingly though, your data doesn't seem to have any pumps, blowers or other accessories. The iOS app only shows two lights. Is this what you'd expect?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>



gazoodle left a comment (gazoodle/geckolib#35)
Thanks for that. I think that's enough data to ensure I handle it correctly. The simulator and iOS app seem to function as expected. Interestingly though, your data doesn't seem to have any pumps, blowers or other accessories. The iOS app only shows two lights. Is this what you'd expect?

**Comment by gazoodle** [comment]
Fixed in v1.0.2 and HA integration v0.1.19
