### ISSUE TITLE
Problem getting async example to work

### ISSUE THREAD

**Issue by gizmocuz** [gazoodle/geckolib#36]
Thanks for the great library!

Shell usage is working great...

Now I am trying to get the async sample from the readme to work.

At the top I changed the following parameters

CLIENT_ID = "02ac6d28-xxxx-xxxx-xxxx-274d0aa491da"
SPA_ADDRESS = "192.168.42.123"

When I run the example I get the following error:

> e:\Test\python async.py
> GeckoSpaEvent.SPA_MAN_ENTER: {}
> Looking for spas on your network ...
> GeckoSpaEvent.LOCATING_STARTED: {}
> 2023-02-18 17:56:56,565> ERROR GeckoAsyncUdpProtocol: Exception received [WinError 10022] An invalid argument was supplied
> Traceback (most recent call last):
>   File "C:\Python310-32\lib\asyncio\proactor_events.py", line 568, in _loop_reading
>     self._read_fut = self._loop._proactor.recvfrom(self._sock,
>   File "C:\Python310-32\lib\asyncio\windows_events.py", line 499, in recvfrom
>     ov.WSARecvFrom(conn.fileno(), nbytes, flags)
> OSError: [WinError 10022] An invalid argument was supplied
> GeckoSpaEvent.LOCATING_FINISHED: {'spa_descriptors': []}
> **** There were no spas found on your network.
> GeckoSpaEvent.SPA_MAN_EXIT: {'exc_info': (None, None, None)}

**Comment by gazoodle** [comment]
Hmmm. Might be Windows related, some of the samples will only run on Linux, the more complicated the less chance there is of them working. The trivial samples ought to work OK ...
