### ISSUE TITLE
Help needed with connection error handling using geckolib

### ISSUE THREAD

**Issue by rrov1** [gazoodle/geckolib#37]
Hi,

I'm trying to use geckolib to change the watercare mode. I was successfull to adpot the example script and it works in the most calls, but sometimes it has a problem during connection esteblishment. So I decided to add some code to catch the error an call async_reset() but it won't work as expected. Because I  use Python-language not very often, I would ask for help/suggestions. What I also need to say is, that there is another script running in background every minute that connects in the same manner and read's out some values and writes them away.

I created the following code, it's the "Async API Usage"-expamle with an modified main()-function:
```
async def main() -> None:

    async with SampleSpaMan(CLIENT_ID, spa_identifier=SPA_ID) as spaman:
        print("Looking for spas on your network ...")
        
        connectAttemptCount = 0
        connectSuccess = False
        while not connectSuccess and connectAttemptCount < 2:
            try:
                print(f"*** connecting to spa (attempt: {connectAttemptCount + 1})")
                # Wait for descriptors to be available
                await spaman.wait_for_descriptors()

                if len(spaman.spa_descriptors) == 0:
                    print("*** there were no spas found on your network.")
                    quit(-1)

                await spaman.async_connect(spa_identifier=SPA_ID)

                # Wait for the facade to be ready
                await spaman.wait_for_facade()

                currentWatercareMode = spaman.facade.water_care.active_mode
            except Exception as e:
                print(e)
                print(f"error: unable to connect to spa: {SPA_ID}")
                connectAttemptCount = connectAttemptCount + 1

                # reset spaman
                await spaman.async_reset()
            else:
                print("*** connection successfull created")
                connectSuccess = True

        if not connectSuccess:
            print(f"error: unable to connect to spa controller after {connectAttemptCount - 1} attempts")
            quit(-1)

        # set water care mode
        await spaman.facade.water_care.async_set_mode(spaman.facade.water_care.modes[0])

        # ende
        print("*** end")
        return
```
If the connection error happens to log is (canceled by ctrl-c):

```
GeckoSpaEvent.SPA_MAN_ENTER: {}
Looking for spas on your network ...
*** connecting to spa (attempt: 1)
GeckoSpaEvent.LOCATING_STARTED: {}
GeckoSpaEvent.LOCATING_DISCOVERED_SPA: {'spa_descriptor': Whirlpool Rico(SPA68:aa:bb:cc:dd:ee)}
GeckoSpaEvent.LOCATING_DISCOVERED_SPA: {'spa_descriptor': SwimSpa Peggy(SPA68:aa:bb:cc:dd:ff)}
2023-02-26 18:23:07,538> INFO Found 2 spas ... [Whirlpool Rico(SPA68:aa:bb:cc:dd:ee), SwimSpa Peggy(SPA68:aa:bb:cc:dd:ff)]
GeckoSpaEvent.LOCATING_FINISHED: {'spa_descriptors': [Whirlpool Rico(SPA68:aa:bb:cc:dd:ee), SwimSpa Peggy(SPA68:aa:bb:cc:dd:ff)]}
GeckoSpaEvent.LOCATING_STARTED: {}
GeckoSpaEvent.LOCATING_STARTED: {}
GeckoSpaEvent.LOCATING_DISCOVERED_SPA: {'spa_descriptor': SwimSpa Peggy(SPA68:aa:bb:cc:dd:ff)}
GeckoSpaEvent.LOCATING_FINISHED: {'spa_descriptors': [SwimSpa Peggy(SPA68:aa:bb:cc:dd:ff)]}
GeckoSpaEvent.CLIENT_HAS_STATUS_SENSOR: {}
GeckoSpaEvent.CLIENT_HAS_RECONNECT_BUTTON: {}
GeckoSpaEvent.CONNECTION_STARTED: {}
GeckoSpaEvent.RUNNING_PING_RECEIVED: {'last_ping_at': datetime.datetime(2023, 2, 26, 17, 23, 7, 576750, tzinfo=datetime.timezone.utc)}
GeckoSpaEvent.CONNECTION_GOT_FIRMWARE_VERSION: {'intouch_version_en': '88 v15.0', 'intouch_version_co': '89 v11.0'}
GeckoSpaEvent.CLIENT_HAS_PING_SENSOR: {}
GeckoSpaEvent.CONNECTION_GOT_CHANNEL: {'channel': 31, 'signal': 94}
GeckoSpaEvent.CONNECTION_GOT_CONFIG_FILES: {'plateform_key': 'inyt', 'config_version': 65, 'log_version': 66}
GeckoSpaEvent.CONNECTION_INITIAL_DATA_BLOCK_REQUEST: {}
GeckoSpaEvent.LOCATING_FINISHED: {'spa_descriptors': []}
GeckoSpaEvent.SPA_NOT_FOUND: {'spa_address': None, 'spa_identifier': 'SPA68:aa:bb:cc:dd:ff'}
'NoneType' object has no attribute 'water_care'
error: unable to connect to spa: SPA68:aa:bb:cc:dd:ff
GeckoSpaEvent.RUNNING_SPA_DISCONNECTED: {}
*** connecting to spa (attempt: 2)
2023-02-26 18:23:21,487> ERROR Exception during spa connection
Traceback (most recent call last):
  File "/home/rrov1/.local/lib/python3.9/site-packages/geckolib/async_spa.py", line 367, in connect
    await self._connect()
  File "/home/rrov1/.local/lib/python3.9/site-packages/geckolib/async_spa.py", line 334, in _connect
    if not await self.struct.get(
  File "/home/rrov1/.local/lib/python3.9/site-packages/geckolib/driver/async_spastruct.py", line 64, in get
    request = create_func()
  File "/home/rrov1/.local/lib/python3.9/site-packages/geckolib/async_spa.py", line 337, in <lambda>
    self._protocol.get_and_increment_sequence_counter(False),
AttributeError: 'NoneType' object has no attribute 'get_and_increment_sequence_counter'
GeckoSpaEvent.CONNECTION_FINISHED: {'facade': None}
2023-02-26 18:24:03,538> ERROR Task exception was never retrieved
future: <Task finished name='SPAMAN:Sequence Pump' coro=<GeckoAsyncSpaMan._sequence_pump() done, defined at /home/rrov1/.local/lib/python3.9/site-packages/geckolib/async_spa_manager.py:524> exception=AttributeError("'NoneType' object has no attribute 'get_and_increment_sequence_counter'")>
Traceback (most recent call last):
  File "/home/rrov1/.local/lib/python3.9/site-packages/geckolib/async_spa_manager.py", line 543, in _sequence_pump
    await self.async_connect(self._spa_identifier, self._spa_address)
  File "/home/rrov1/.local/lib/python3.9/site-packages/geckolib/async_spa_manager.py", line 334, in async_connect
    return await self.async_connect_to_spa(spa_descriptors[0])
  File "/home/rrov1/.local/lib/python3.9/site-packages/geckolib/async_spa_manager.py", line 300, in async_connect_to_spa
    await self._spa.connect()
  File "/home/rrov1/.local/lib/python3.9/site-packages/geckolib/async_spa.py", line 367, in connect
    await self._connect()
  File "/home/rrov1/.local/lib/python3.9/site-packages/geckolib/async_spa.py", line 334, in _connect
    if not await self.struct.get(
  File "/home/rrov1/.local/lib/python3.9/site-packages/geckolib/driver/async_spastruct.py", line 64, in get
    request = create_func()
  File "/home/rrov1/.local/lib/python3.9/site-packages/geckolib/async_spa.py", line 337, in <lambda>
    self._protocol.get_and_increment_sequence_counter(False),
AttributeError: 'NoneType' object has no attribute 'get_and_increment_sequence_counter'
^CGeckoSpaEvent.SPA_MAN_EXIT: {'exc_info': (<class 'asyncio.exceptions.CancelledError'>, CancelledError(), <traceback object at 0x7f6717f2ea80>)}
Traceback (most recent call last):
  File "/home/rrov1/spa_setWatercareMode.py", line 140, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1854, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.9/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt
```

Any suggestions are welcome.

rrov1

**Comment by gazoodle** [comment]
Did you create a different CLIENT_ID for each script? I have to say the Gecko devices do struggle with connection issues when there is more than one client talking to them. The in.touch2 hardware uses UDP which isn’t really designed for full duplex communication. If you’re in control of both scripts, it probably makes sense to combine them so that you only need one connection which is shared between your two tasks.

**Comment by rrov1** [comment]
Hi,
no currently I use the same CLIENT_ID in all scripts, because sometimes I had errors related to network pakets with the wrong GUID. I will follow your suggestion and change the scripts in way that there will be only one script running at a time. 

Thank you for your help.
