### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by AlbertHakvoort** [gazoodle/geckolib#40]
I get the following error

Starting discovery process...Found 1 spas
Connecting to spa `Wellis` at 172.xx.xx.xx ... connected!
Heater: Temperature 37.0°C, SetPoint 34.0°C, Real SetPoint 34.0°C, Operation Cooling
Pump 1: OFF
Lights: OFF
WaterCare: Waiting...
Smart Winter Mode:Risk: NO
Circulating Pump: OFF
Ozone: OFF
Smart Winter Mode:Active: False
Filter Status:Clean: False
Filter Status:Purge: False
Economy Mode: False
Error Sensor: VSP1CommLost, VSP2CommLost
Welcome to the Gecko shell. Type help or ? to list commands.

Wellis$ LOG> ERROR Unhandled exception in receive_handler func
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/geckolib/driver/udp_socket.py", line 181, in dispatch_recevied_data
    receive_handler.handled(remote_end)
  File "/usr/local/lib/python3.9/dist-packages/geckolib/driver/udp_protocol_handler.py", line 101, in handled
    self._on_handled(self, sender)
  File "/usr/local/lib/python3.9/dist-packages/geckolib/automation/watercare.py", line 64, in _on_watercare
    self._on_change(self, old_mode, self.active_mode)
  File "/usr/local/lib/python3.9/dist-packages/geckolib/driver/observable.py", line 39, in _on_change
    f"{self.__class__.__name__} {sender} changed "
  File "/usr/local/lib/python3.9/dist-packages/geckolib/automation/watercare.py", line 92, in __str__
    return f"{self.name}: {GeckoConstants.WATERCARE_MODE_STRING[self.active_mode]}"
IndexError: list index out of range

**Comment by AlbertHakvoort** [comment]
If nothing selected in the scheduler, it wil send a empty state. I added a extra MODE state to solve the error

WATERCARE_MODE = (
        AwayFromHome,
        Standard,
        EnergySaving,
        SuperEnergySaving,
        Weekender,
        NotSet,
    ) = range(6)

    WATERCARE_MODE_STRING = [
        "Away From Home",
        "Standard",
        "Energy Saving",
        "Super Energy Saving",
        "Weekender",
        "Not Set",

**Comment by AlbertHakvoort** [comment]
![photo_2023-07-13_15-27-07](https://github.com/gazoodle/geckolib/assets/23001971/8742f413-24ce-4158-b16e-4bb17f952966)

After selecting the Mode the problem is also solved.. You can't deselect it ;)

**Comment by gazoodle** [comment]
Fixed in v0.4.16
