### ISSUE TITLE
Bain Ultra tub in.touch2 / invalid driver pack

### ISSUE THREAD

**Issue by sethgregory** [gazoodle/geckolib#41]
Hi there, trying to use GeckoShell to connect to my Bain Ultra tub that uses an in.Touch2 for remote access and not having much luck; looks like a nonexistent driver pack based on the platform key received.  Anything I could do to help add support for these models?

Error is as follows:
`>>> GeckoShell.run()

        <Disclaimer>
        ----------------------------- USE AT YOUR OWN RISK -----------------------------

        This code will allow you to make changes to your spa configuration that is
        outside of what the app, top panel and side panel settings allow. I've not
        tested every setting and it might be that you prevent your spa pack from
        operating as it used to do.

        I strongly suggest dumping the configuration values with the "config" command
        and recording them somewhere safe.

        </Disclaimer>

Starting discovery process...Found 1 spas
Connecting to spa `Meridian 55` at 192.168.0.245 ... LOG> ERROR Unhandled exception in receive_handler func
Traceback (most recent call last):
  File "/home/sgregory/.local/lib/python3.7/site-packages/geckolib/spa.py", line 114, in _on_config_received
    GeckoPack = importlib.import_module(pack_module_name).GeckoPack
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'geckolib.driver.packs.masi'`

**Comment by gazoodle** [comment]
Worth checking again with v0.4.15 as it has the latest SpaPackStruct in

**Comment by gazoodle** [comment]
We need the XML file for this. It's not in the latest from Gecko, without it we can't control the unit. I suggest looking at the conversation between the App and their servers during startup to see if they have a custom XML file that you can intercept and add to this issue.

**Comment by gazoodle** [comment]
@sethgregory Are you still interested in support for your Bain Ultra tub? I've found the data in the Gecko library by guessing and fiddling around I've managed to get the BU-Touch app to connect to my simulator.

I've got some ideas how to progress but will need some diagnostics from your actual device if that's ok?

**Comment by sethgregory** [comment]
Hey there, thanks for reaching out. I've not made any progress on my own so far but I'm definitely up for it. Just let me know what you need.

**Comment by gazoodle** [comment]
If you can repeat the shell exercise again, but make sure you have debug logging enabled, I will be able to see the protocol and we can go from there.

**Comment by gazoodle** [comment]
Actually, wait for the next release, I’ll make sure there is more diags in there so we can skip several iterations

**Comment by gazoodle** [comment]
@sethgregory, Ok. v1.0.12 has the necessary, please do the install and run the shell as per above and then get the log file here please. Thank you

**Comment by sethgregory** [comment]
Sorry, let's try this again.  The above log was invalid, the LED was green on the receiver so it somehow lost connection.  Power cycled and tried again and this looks more promising: [shell.log](https://github.com/user-attachments/files/19130291/shell.log)

**Comment by gazoodle** [comment]
Should be functional now. The integration for Home Assistant ought to find the bath and give you controls to manage it now. I'm going to close this issue now, if there are any problems, can you open issues against the HA integration? Thanks
