### ISSUE TITLE
Windows Integration for Async

### ISSUE THREAD

**Issue by mcsSolutions** [gazoodle/geckolib#53]
I have tried the sample Async usage shown in the description and the complete.py on a Windows 11 platform.  The following console feedback was provided showing error traps.  GeckoSample.py is just a copy/paste from the github description of how to use the Async library.

The first of the complete.py attempt was resolved with install of windows-curses.  The others are unresolved.  

I am not a Python programmer so it is difficult to dig deeper.

C:\Users\mcsSo\AppData\Local\Programs\Python\Python312>python C:\Users\mcsSo\AppData\Local\Programs\Python\Python312\Scripts\GeckoSample.py
Looking for spas on your network ...
2024-11-26 13:09:49,684> ERROR GeckoAsyncUdpProtocol: Exception received [WinError 10022] An invalid argument was supplied
Traceback (most recent call last):
  File "C:\Users\mcsSo\AppData\Local\Programs\Python\Python312\Lib\asyncio\proactor_events.py", line 577, in _loop_reading
    self._read_fut = self._loop._proactor.recvfrom(self._sock,
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mcsSo\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 499, in recvfrom
    ov.WSARecvFrom(conn.fileno(), nbytes, flags)
OSError: [WinError 10022] An invalid argument was supplied
2024-11-26 13:09:49,699> ERROR GeckoAsyncUdpProtocol: Exception received [WinError 10022] An invalid argument was supplied
Traceback (most recent call last):
  File "C:\Users\mcsSo\AppData\Local\Programs\Python\Python312\Lib\asyncio\proactor_events.py", line 537, in _loop_writing
    self._write_fut = self._loop._proactor.sendto(self._sock,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mcsSo\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 529, in sendto
    ov.WSASendTo(conn.fileno(), buf, flags, addr)
OSError: [WinError 10022] An invalid argument was supplied
2024-11-26 13:09:50,812> ERROR GeckoAsyncUdpProtocol: Exception received [WinError 10022] An invalid argument was supplied
-------------------------

C:\Users\mcsSo\AppData\Local\Programs\Python\Python312>python C:\Users\mcsSo\Downloads\geckolib-main\sample\complete.py
Traceback (most recent call last):
  File "C:\Users\mcsSo\Downloads\geckolib-main\sample\complete.py", line 21, in <module>
    from cui import CUI
  File "C:\Users\mcsSo\Downloads\geckolib-main\sample\cui.py", line 10, in <module>
    import curses
  File "C:\Users\mcsSo\AppData\Local\Programs\Python\Python312\Lib\curses\__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'

Resolved with pip install windows-curses

-------------------------

C:\Users\mcsSo\AppData\Local\Programs\Python\Python312>python C:\Users\mcsSo\Downloads\geckolib-main\sample\complete.py
Traceback (most recent call last):
  File "C:\Users\mcsSo\Downloads\geckolib-main\sample\complete.py", line 57, in <module>
    wrapper(main)
  File "C:\Users\mcsSo\AppData\Local\Programs\Python\Python312\Lib\curses\__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mcsSo\Downloads\geckolib-main\sample\complete.py", line 49, in main
    install_logging()
  File "C:\Users\mcsSo\Downloads\geckolib-main\sample\complete.py", line 31, in install_logging
    os.remove("cui.log")
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'cui.log'

**Comment by gazoodle** [comment]
Hmmm, I don't think the `complete.py` will work on Windows, it relies on a bunch of *nix stuff. Sorry.
